name       : lcov
version    : 1.13
release    : 1
source     :
    - http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz : 44972c878482cc06a05fe78eaa3645cbfcbad6634615c3309858b207965d8a23
license    : GPL-2.0
component  : programming.tools
summary    : Frontend to gcov
description: |
    Frontend for the GCC lcov tool
build      : |
    %make
install    : |
    %make PREFIX=$installdir/usr install
    mv $installdir/usr/etc $installdir/.
